import api from './axiosInstance';
export const getSessions = (params) => api.get('/sessions', { params });
export const getSession = (id) => api.get(`/sessions/${id}`);
export const getUpcomingSessions = () => api.get('/sessions/upcoming');
export const getLiveSessions = () => api.get('/sessions/live');
export const createSession = (data) => api.post('/sessions', data);
export const updateSession = (id, data) => api.put(`/sessions/${id}`, data);
export const deleteSession = (id) => api.delete(`/sessions/${id}`);
export const updateMeetLink = (id, meetLink) => api.patch(`/sessions/${id}/meet-link`, { meetLink });
export const goLive = (id) => api.patch(`/sessions/${id}/go-live`);
export const endLive = (id) => api.patch(`/sessions/${id}/end-live`);
