import api from './axiosInstance';
export const getUsers = (params) => api.get('/users', { params });
export const getUser = (id) => api.get(`/users/${id}`);
export const createUser = (data) => api.post('/users', data);
export const updateUser = (id, data) => api.put(`/users/${id}`, data);
export const deleteUser = (id) => api.delete(`/users/${id}`);
export const toggleUserActive = (id) => api.patch(`/users/${id}/toggle-active`);
export const getStudents = (params) => api.get('/students', { params });
export const getStudent = (id) => api.get(`/students/${id}`);
export const getStudentMentor = (id) => api.get(`/students/${id}/mentor`);
export const getStudentSessions = (id) => api.get(`/students/${id}/sessions`);
export const getStudentAttendance = (id) => api.get(`/students/${id}/attendance`);
export const getStudentNotes = (id) => api.get(`/students/${id}/notes`);
export const getStudentHealthScore = (id) => api.get(`/students/${id}/health-score`);
export const searchStudents = (q) => api.get('/students/search', { params: { q } });
export const getTeachers = () => api.get('/teachers');
export const getTeacher = (id) => api.get(`/teachers/${id}`);
export const getTeacherStudents = (id) => api.get(`/teachers/${id}/students`);
export const assignStudent = (teacherId, studentId) => api.post(`/teachers/${teacherId}/assign-student`, { studentId });
export const unassignStudent = (teacherId, studentId) => api.delete(`/teachers/${teacherId}/unassign-student/${studentId}`);
export const getParentChildren = (id) => api.get(`/parents/${id}/children`);
